goals:
  - id: 3
    x: 15.55
    y: 4.6
    theta: 3.142
  - id: 10
    x: 24.5
    y: 10.3
    theta: -1.571
  - id: 11
    x: 29.6
    y: 12.35
    theta: 3.142
  - id: 12
    x: 36.1
    y: 12.4
    theta: 0.0
  - id: 13
    x: 40
    y: 11.7
    theta: 1.571
